repo_paths:
  build_root: "_build"
  logs_root: "_logs"
  conan_lock: "conan_glfw.lock"
  conan_deps_root: "{build_root}/deps"

build:
  windowing: "glfw"
  prebuild:
    format: {}
    slangc:
      compiler_search_roots: "{deps_root}/slang/*/*"
      shaders:
        - input: "assets/shaders/test/*.slang"
          output: "assets/shaders/test/*.wgsl"
  postbuild: {}
  conan:
    local_recipes:
      - name: "slang"
        version: "2026.1"
        path: "tools/conan/slang"
      - name: "dawn"
        version: "20250428.160623"
        path: "tools/conan/dawn"
      - name: "openusd"
        version: "25.02"
        path: "tools/conan/openusd"

launch:
  env:
    PATH:
      - "{deps_root}/openusd/*/{build_type}/*/lib"
      - "{deps_root}/onetbb/*/{build_type}/*/bin"
      - "{deps_root}/dawn/*/{build_type}/*/bin"
